// Generated by https://quicktype.io

export interface Post {
    id:        string;
    title:     string;
    content:   string;
    author:    string;
    slug:      string;
    mark:      boolean;
    tags:      Tag[];
    thumbnail: Thumbnail;
}

export interface Tag {
    id:    string;
    title: string;
    mark:  boolean;
}

export interface Thumbnail {
    colors: Color[];
    url:    string;
}

export interface Color {
    hex: string;
}
